### ISSUE TITLE
Basic Functions (Ban/Signup/Login/Mail/Favorites/Etc)

### ISSUE THREAD

**Issue by samdisk11** [samdisk11/OpenTV#1]
The server has no simple functions other than allowing the box come to a dummy home page.

**Comment by samdisk11** [comment]
searching works now.

**Comment by PajamaFrix** [comment]
> searching works now. 

Doesn't seem to work on actual hardware, given how DDG uses HTTPS and only HTTPS.

-F

**Comment by samdisk11** [comment]
well that sucks, is there any lightweight alternatives?

**Comment by PajamaFrix** [comment]
dunno, but google seems to work for me... besides the fact that they also
use HTTPS for opening links...
